Fix _eghcup invocations

diff --git a/scripts/bootstrap/bootstrap-haskell b/scripts/bootstrap/bootstrap-haskell
--- a/scripts/bootstrap/bootstrap-haskell
+++ b/scripts/bootstrap/bootstrap-haskell
@@ -797,7 +797,7 @@ edo mkdir -p "${GHCUP_BIN}"
 
 if command -V "ghcup" >/dev/null 2>&1 ; then
     if [ -z "${BOOTSTRAP_HASKELL_NO_UPGRADE}" ] ; then
-        _eghcup upgrade || download_ghcup
+        ( _eghcup upgrade ) || download_ghcup
     fi
 else
 	download_ghcup
@@ -844,17 +844,17 @@ fi
 
 case $ask_hls_answer in
 	1)
-		_eghcup --cache install hls || warn "HLS installation failed, continuing anyway"
+        (_eghcup --cache install hls) || warn "HLS installation failed, continuing anyway"
 		;;
 	*) ;;
 esac
 
 case $ask_stack_answer in
 	1)
-		_eghcup --cache install stack || die "Stack installation failed"
+        (_eghcup --cache install stack) || die "Stack installation failed"
 		;;
 	2)
-		_eghcup --cache install stack || die "Stack installation failed"
+        (_eghcup --cache install stack) || die "Stack installation failed"
         edo mkdir -p "${STACK_ROOOT:-$HOME/.stack}"/hooks
         hook_exe="${STACK_ROOOT:-$HOME/.stack}"/hooks/ghc-install.sh
         hook_url="https://www.haskell.org/ghcup/sh/hooks/stack/ghc-install.sh"
